- name: Disable swap
  ansible.builtin.command: swapoff -a

- name: Ensure swap is disabled on boot
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s)'
    replace: '# \1'