---
- name: Download the Kubernetes GPG key
  get_url:
    url: "https://pkgs.k8s.io/core:/stable:/{{ k8s_version }}/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg"
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    mode: '0644'

- name: Download and save Kubernetes GPG key
  shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.33/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Update apt package index
  apt:
    update_cache: yes

- name: Install kubelet, kubeadm, and kubectl
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Hold
  dpkg_selections:
    name: kubeadm
    selection: hold
    
- name: Hold
  dpkg_selections:
    name: kubelet
    selection: hold

- name: Hold
  dpkg_selections:
    name: kubectl
    selection: hold

# - name: Hold Kubernetes packages
#   command: apt-mark hold kubelet kubeadm kubectl
