---
- name: Copy InitConfiguration manifest
  ansible.builtin.copy:
    src: files/node.yaml
    dest: /tmp/node.yaml



- name: kubeadm init
  ansible.builtin.shell: "{{ hostvars[groups['master'][0]].kubeadm_join_cmd }}"
  when: hostvars[groups['master'][0]].kubeadm_join_cmd is defined
