---
- name: Copy InitCluster manifest to the k8s master
  ansible.builtin.copy:
    src: files/master.yaml
    dest: /tmp/master.yaml
    mode: '0644'

- name: kubeadm init
  ansible.builtin.shell: kubeadm init --config /tmp/master.yaml

- name: Create /root/.kube directory
  ansible.builtin.file:
    state: directory
    path: /root/.kube

- name: Create symlink for 
  ansible.builtin.file:
    state: link
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config

# Copying k8s bootstrap token
- name: Create K8s bootstrap token
  ansible.builtin.shell: kubeadm token create
  register: bootstrap_token

- name: Save K8s bootstrap token
  ansible.builtin.set_fact:
    kubeadm_join_cmd: "{{ bootstrap_token.stdout }}"

# Saving CA certificate hash for building trust between k8s control-plane and nodes
- name: Get CA certificate hash
  ansible.builtin.shell: "openssl x509 -in /etc/kubernetes/pki/ca.crt -noout -pubkey | openssl rsa -pubin -outform DER 2>/dev/null | sha256sum | cut -d' ' -f1"
  register: kubeadm_ca_hash

- name: Save K8s CA certificate hash
  ansible.builtin.set_fact:
    kubeadm_join_crt_hash: "{{ kubeadm_ca_hash.stdout }}"

- name: Install Calico
  ansible.builtin.shell: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/calico.yaml